on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ProjectPlus.flatpak
        manifest-path: com.projectplusgame.ProjectPlus.yml
        cache-key: flatpak-builder-${{ github.sha }}
